name: KubeGuard-Scan

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

  sast-semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/python p/security-audit"

  sast-bandit:
    name: Bandit SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r . -ll
  
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit 
        run: |
          if [ -f controller/requirements.txt ]; then pip-audit -r controller/requirements.txt
          
          else echo "No requirements.txt found, skipping pip-audit"
          fi       

      - name: Run Trivy FS scan 
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs" 
          format: "table" 
          exit-code: "1"
          severity: "HIGH,CRITICAL"

  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

        # This builds the image locally on the GitHub Runner
      - name: Build Docker Image
        run: docker build -t kubeguard-controller:${{ github.sha }} ./controller
        
        # This scans that specific image for OS-level vulnerabilities
      
      - name: Run Trivy Image scan 
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: kubeguard-controller:${{ github.sha }}
          format: table
          exit-code: "1"
          severity: "CRITICAL"

